Add action to publish jvm/android packages and move to maintained rust toolchain
wireapp/core-crypto pull request #157
Opened 2022-10-24 14:45 UTC by augustocdias

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Adds a step in the CI to publish JVM and Android packages.

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-10-26 11:52 UTC, typfel commented on .github/workflows/publish-jvm.yml
> +          git commit -am "Release of core-crypto $GITHUB_REF_NAME"
```suggestion
          git commit -am "chore: release of core-crypto $GITHUB_REF_NAME"
```

2022-10-26 14:55 UTC, OtaK requested changes

2022-10-26 14:55 UTC, OtaK commented on .github/workflows/docs.yml
>          target: wasm32-unknown-unknown
```suggestion
        targets: wasm32-unknown-unknown
```

2022-10-26 15:34 UTC, augustocdias commented on .github/workflows/rust.yml
> +      - run: cargo fmt --all -- --check
Unmaintained project

2022-10-27 09:19 UTC, OtaK requested changes
I guess it's just missing a rebase + squash now

2022-10-27 14:43 UTC, augustocdias commented
> I guess it's just missing a rebase + squash now

We're changing it to publish to github packages instead of a separate repo

2022-10-27 15:45 UTC, typfel approved these changes

2022-10-28 07:33 UTC, merged

2022-10-28 08:38 UTC, OtaK commented
> > I guess it's just missing a rebase + squash now
> 
> We're changing it to publish to github packages instead of a separate repo

I don't get it. Squash was needed to avoid this: 
![image](https://user-images.githubusercontent.com/1262712/198543787-b69ba272-5887-4f6a-abd5-ec1201ffb273.png)

2022-10-28 08:59 UTC, augustocdias commented
> > > I guess it's just missing a rebase + squash now
> > 
> > 
> > We're changing it to publish to github packages instead of a separate repo
> 
> I don't get it. Squash was needed to avoid this: ![image](https://user-images.githubusercontent.com/1262712/198543787-b69ba272-5887-4f6a-abd5-ec1201ffb273.png)
> 
> Also the fact that none of the commits respect conventional commits

It was squashed on merge. Why does it matter what is in this branch (which I deleted by the way). There's only one commit on develop. 

Also we're publishing a package now. If you check the side bar on the right of our repo you'll notice this now:

![image](https://user-images.githubusercontent.com/1080789/198548000-fd80b5e0-9e1c-4be9-9c4e-7a11dd810b18.png)