feat: add end to end identity bindings [CL-21]
wireapp/core-crypto pull request #217
Opened 2023-01-17 14:35 UTC by beltram

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Add end to end identity bindings for Android. WASM support is partial and to be continued. Swift bindings are not done.

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-01-17 15:05 UTC, OtaK requested changes

2023-01-17 15:05 UTC, OtaK commented on crypto-ffi/src/wasm.rs
> +#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
Unsure but you might need to add something like `#[serde(rename_all = "camelCase")]` for the JSON conversion to happen correctly between the JS naming schemes and the rust-native `snake_case`

2023-01-17 15:05 UTC, OtaK commented on crypto/src/e2e_identity/types.rs
> +pub struct E2eiAcmeDirectory {
same here as with the TS/WASM conversions, you might need a `#[serde(rename_all = "camelCase")]` directive

2023-01-17 15:05 UTC, OtaK commented on crypto/src/e2e_identity/types.rs
> +pub struct E2eiNewAcmeAuthz {
Same possible JSON serialization issues with the casing here

2023-01-17 15:14 UTC, merged

2023-01-20 10:52 UTC, beltram commented on crypto-ffi/src/generic.rs
> +        access_token_url: String,
Hmmm that would require maintaining yet another struct across the FFI which might be cumbersome to maintain