fix: E2EI mobile FFI
wireapp/core-crypto pull request #323
Opened 2023-05-17 13:40 UTC by beltram

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

mobile FFI was failing when initializing MLS client due to a Arc being incremented one too many times. Also add the E2EI API in the Kotlin wrapper and a test for it

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-05-17 13:52 UTC, typfel approved these changes

2023-05-22 10:43 UTC, OtaK requested changes

2023-05-22 10:43 UTC, OtaK commented on crypto-ffi/src/generic.rs
> +        unsafe {
Wrap this in an `if Arc::strong_count(&enrollment) > 1` statement

2023-05-22 11:32 UTC, OtaK approved these changes

2023-05-22 12:41 UTC, merged