feat!: buffer messages from future epochs [WPB-3786]
wireapp/core-crypto pull request #383
Opened 2023-08-10 13:31 UTC by beltram

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Regular group members were also impacted by unordered messages. As a consequence, messages from future epochs are now buffered.

* `decryptMessage` might throw a `BufferedFutureMessage` error which you should catch & ignore
* `commitAccepted` now returns an optional list of decrypted messages

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-08-14 06:45 UTC, OtaK requested changes

2023-08-14 06:45 UTC, OtaK commented on crypto-ffi/bindings/js/CoreCrypto.ts
> +     * @returns eventually the buffered messages from current epoch which had been buffered
```suggestion
     * @returns the messages from current epoch which had been buffered, if any
```

2023-08-14 06:45 UTC, OtaK commented on crypto-ffi/bindings/js/CoreCrypto.ts
> +     * @returns eventually the buffered messages from current epoch which had been buffered
```suggestion
     * @returns the messages from current epoch which had been buffered, if any
```

2023-08-14 11:59 UTC, OtaK approved these changes
LGTM once tests pass

2023-08-17 12:34 UTC, merged

2023-08-17 14:18 UTC, typfel commented
@beltram sorry a bit late on this one but why do I get the buffered messages on `commitAccepted`? AFAIK `commitAccepted` is called when I myself have advanced the epoch so how can someone else possibly else send a message in this not yet existing epoch?

And what if I receive message out of order and they are buffered and I never advance the epoch? Then I never receive the buffered messages?

2023-08-17 15:40 UTC, beltram commented
> why do I get the buffered messages on commitAccepted? AFAIK commitAccepted is called when I myself have advanced the epoch so how can someone else possibly else send a message in this not yet existing epoch ?

You're right that does not make sense, this should be on `decryptMessage()`, I'll fix that.

> And what if I receive message out of order and they are buffered and I never advance the epoch? Then I never receive the buffered messages ?

Well in that case you are screwed. We cannot do anything about it

2023-08-17 15:49 UTC, typfel commented
> > why do I get the buffered messages on commitAccepted? AFAIK commitAccepted is called when I myself have advanced the epoch so how can someone else possibly else send a message in this not yet existing epoch ?
> 
> You're right that does not make sense, this should be on `decryptMessage()`, I'll fix that.
> 
> > And what if I receive message out of order and they are buffered and I never advance the epoch? Then I never receive the buffered messages ?
> 
> Well in that case you are screwed. We cannot do anything about it

I was thinking I when receive an incoming commit I would get the buffered messages for that commit.