feat: Add ability to manually seed the PRNG entropy pool [CL-38]
wireapp/core-crypto pull request #59
Opened 2022-07-12 16:35 UTC by OtaK

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Ability to insert external entropy from outside of `getrandom`

### Solutions

* Added an ability to insert external entropy from outside of `getrandom`
* Added support for P384 ciphersuites
	* Note: P521 code is ready but the Rust `p521` crate is not ready yet
	* Note: Ed448 support is an unknown. There's no official RustCrypto crate for it and the others are very much manual things and getting your hands dirty

### Testing

#### Test Coverage

- [x] I have added automated test to this contribution

#### How to Test

```
cd mls-provider
cargo test
```

### Notes (Optional)

A lot of parametric tests have been added to the MLS provider, to test using all the scenarios: storage backends, ciphersuites, etc

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-07-15 11:43 UTC, beltram requested changes

2022-07-15 11:46 UTC, OtaK commented on crypto-ffi/src/wasm.rs
> +            configuration.set_entropy(owned_seed);
What do you think if I make a newtype that wraps the `[u8; 32]` entropy seed type and implement a `from_slice` method there? Would be cleaner with less code repetition

2022-07-15 11:51 UTC, beltram commented on crypto-ffi/src/wasm.rs
> +            configuration.set_entropy(owned_seed);
IIRC `EntropySeed` is already a [u8; 32].  
But I agree `EntropySeed` could be a tuple struct and you could impl `from_slice` on it

2022-07-18 12:00 UTC, beltram approved these changes

2022-07-18 14:48 UTC, merged